name: CI
on:
  push:
    branches:
      - '*'
    #   - master
    # tags:
    #   - v*

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0

      - run: npm install
      - run: npm run build
      - run: npm run test:ci

      - run: npm install @jsdevtools/npm-publish -g
      - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./package.json

      # - name: Create Tag
      #   id: create_tag
      #   uses: jaywcjlove/create-tag-action@v1.3.6 https://github.com/rickstaa/action-create-tag/issues/26
      #   with:
      #     package-path: ./package.json

      # - name: get tag version
      #   id: tag_version
      #   uses: jaywcjlove/changelog-generator@v1.5.3

      # - name: Build and Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: master
